# Site settings
title_left    : "general abstract"
title_right   : " nonsense" # default: ""
description   : "Computer Science Student at Princeton University"
keywords      : "personal, website, site, computer, science, software, developer, blog"
url           : https://alanjding.github.io # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

# google_analytics  : UA-XXXXX-XX
# twitter_username  : ""
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Alan Ding"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
  - slug : resume
    title: Resume

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script", "vendor"]
